### PR TITLE
patchelf is only needed on Linux, and is already a dependency of conda-build

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by bjodah** [comment]
Thanks - do you think this was the source of the error?
I'll rerun the Python 3.4 test when in master to see if I can make it fail by simply rerunning it...

**Comment by asmeurer** [comment]
No, it was just preventing me from building on OS X (I still wasn't able to because those other packages don't have OS X builds).

**Comment by bjodah** [comment]
I see, both packages are pure python. How can I indicate that a package is crossplatorm using conda/binstar? i.e. if I'm not compiling any binaries I shouldn't really need access to windows/OS X, right?

**Comment by bjodah** [comment]
still failing on my drone ci server by the way:

http://hera.physchem.kth.se:8080/github.com/bjodah/pybestprac/commit/cfb187195fe8b034610801bd71467d40dd5b6548?branch=master

**Comment by bjodah** [comment]
and restarting the (initially passing) travis job made it fail:
https://travis-ci.org/bjodah/pybestprac/jobs/39860494

**Comment by asmeurer** [comment]
We are working on ways to make this easier, but for now, you can use `conda convert` to convert a pure Python package to all platforms.

**Comment by bjodah** [comment]
ok, great - had missed that tool up till now. I gave it a shot and uploaded Mac OS X packages for those dependencies.

**Pull request merged**
